// This JavaScript file was generated by Yggdrassil on Saturday, November 20, 2021; 9:50:32 AM

let PageLangs = {}
PageLangs.List=[]
PageLangs.Names={}

PageLangs.List[PageLangs.List.length] = 'NL'
PageLangs.Names['NL']='Dutch'

