// This JavaScript file was generated by Yggdrassil on Tuesday, September 7, 2021; 8:47:21 PM

let PageLangs = {}
PageLangs.List=[]
PageLangs.Names={}

PageLangs.List[PageLangs.List.length] = 'NL'
PageLangs.Names['NL']='Dutch'

PageLangs.List[PageLangs.List.length] = 'EN'
PageLangs.Names['EN']='English'

PageLangs.List[PageLangs.List.length] = 'DE'
PageLangs.Names['DE']='German'

PageLangs.List[PageLangs.List.length] = 'FR'
PageLangs.Names['FR']='French'

PageLangs.List[PageLangs.List.length] = 'ES'
PageLangs.Names['ES']='Spanish'

