// This JavaScript file was generated by Yggdrassil on Thursday, September 16, 2021; 11:55:19 AM

let PageLangs = {}
PageLangs.List=[]
PageLangs.Names={}

PageLangs.List[PageLangs.List.length] = 'NL'
PageLangs.Names['NL']='Dutch'

