// This JavaScript file was generated by Yggdrassil on Thursday, September 16, 2021; 3:17:34 PM

let PageLangs = {}
PageLangs.List=[]
PageLangs.Names={}

PageLangs.List[PageLangs.List.length] = 'NL'
PageLangs.Names['NL']='Dutch'

