// This JavaScript file was generated by Yggdrassil on Wednesday, September 8, 2021; 3:18:15 PM

let PageLangs = {}
PageLangs.List=[]
PageLangs.Names={}

PageLangs.List[PageLangs.List.length] = 'NL'
PageLangs.Names['NL']='Dutch'

