// This JavaScript file was generated by Yggdrassil on Tuesday, September 7, 2021; 7:46:14 PM

let PageLangs = {}
PageLangs.List=[]
PageLangs.Names={}

PageLangs.List[PageLangs.List.length] = 'NL'
PageLangs.Names['NL']='Dutch'

