// This JavaScript file was generated by Yggdrassil on Wednesday, September 8, 2021; 6:33:29 AM

let PageLangs = {}
PageLangs.List=[]
PageLangs.Names={}

PageLangs.List[PageLangs.List.length] = 'NL'
PageLangs.Names['NL']='Dutch'

